apiVersion: apps/v1
kind: Deployment
metadata:
  name: Oracle-web-app-deployment
spec:
  replicas: 9
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - name: oracle
        image: muralisocial123/college-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
