apiVersion: v1
kind: Service
metadata:
  name: oracle-app-svc
spec:
  selector:
    app: oracle
  ports:
  - name: oracle
    port: 81
    targetPort: 80
    protocol: TCP
type: LoadBalancer 
